In [27]:
import numpy as np

In [36]:
grades_list = [
    [85, 78, 92, 88],
    [70, 76, 80, 65],
    [90, 88, 94, 91],
    [60, 65, 58, 62],
    [100, 95, 98, 97]]

In [37]:
grades = np.array(grades_list, dtype=float)

In [38]:
print("Shape:", grades.shape)

Shape: (5, 4)


In [39]:
mean_per_student = grades.mean(axis=1)
print("Mean per student:", mean_per_student)

Mean per student: [85.75 72.75 90.75 61.25 97.5 ]


In [40]:
mean_per_subject = grades.mean(axis=0)
print("Mean per subject:", mean_per_subject)

Mean per subject: [81.  80.4 84.4 80.6]


In [41]:
high_avg_mask = mean_per_student > 85
students_high_avg = grades[high_avg_mask]
print("Mask of students with avg > 85:", high_avg_mask)
print("Students (rows) with avg > 85:\n", students_high_avg)

Mask of students with avg > 85: [ True False  True False  True]
Students (rows) with avg > 85:
 [[ 85.  78.  92.  88.]
 [ 90.  88.  94.  91.]
 [100.  95.  98.  97.]]


In [42]:
bonus_grades = grades + 5
print("Grades after +5 bonus:\n", bonus_grades)

Grades after +5 bonus:
 [[ 90.  83.  97.  93.]
 [ 75.  81.  85.  70.]
 [ 95.  93.  99.  96.]
 [ 65.  70.  63.  67.]
 [105. 100. 103. 102.]]


In [43]:
col_min = grades.min(axis=0)
col_max = grades.max(axis=0)
normalized = (grades - col_min) / (col_max - col_min)
print("Min-Max normalized (per subject):\n", normalized)

Min-Max normalized (per subject):
 [[0.625      0.43333333 0.85       0.74285714]
 [0.25       0.36666667 0.55       0.08571429]
 [0.75       0.76666667 0.9        0.82857143]
 [0.         0.         0.         0.        ]
 [1.         1.         1.         1.        ]]


In [44]:
flattened = grades.ravel()
print("Flattened vector:", flattened)

Flattened vector: [ 85.  78.  92.  88.  70.  76.  80.  65.  90.  88.  94.  91.  60.  65.
  58.  62. 100.  95.  98.  97.]
