In [3]:
import numpy as np

In [4]:
X = np.array([50, 60, 80, 100, 120], dtype=float)
y = np.array([150, 180, 240, 300, 330], dtype=float)
print(X)
print(y)

[ 50.  60.  80. 100. 120.]
[150. 180. 240. 300. 330.]


In [6]:
X_col = X.reshape(-1, 1)
print(X_col)

[[ 50.]
 [ 60.]
 [ 80.]
 [100.]
 [120.]]


In [7]:
m = X_col.shape[0]
X_b = np.hstack([np.ones((m, 1)), X_col])
print(X_b)

[[  1.  50.]
 [  1.  60.]
 [  1.  80.]
 [  1. 100.]
 [  1. 120.]]


In [9]:
XtX = X_b.T @ X_b
XtX_inv = np.linalg.inv(XtX)
Xty = X_b.T @ y
theta = XtX_inv @ Xty
print("θ (bias, slope):", theta)

θ (bias, slope): [22.5         2.65243902]


In [10]:
x_new = np.array([1.0, 90.0])
pred_90 = float(x_new @ theta)
print("Predicted price for 90 m² (in thousands):", pred_90)

Predicted price for 90 m² (in thousands): 261.21951219512164
